language: R
cache: packages

r:
  - oldrel
  - release
  - devel

env:
  matrix:
    secure: fygiZB0giuJUpmsLxZvlSEdvkUkd9w/vs631fclI5us7SKpYqNnutofZu0uZVnyXnXjkDsGVLNmLAyU/ChBJH32qKX7G1cyD06e0Vl8+UyaIg8BpahTMlM9cTbqxpb8jukOB2BTue1HvhaqCcR1TuXyaFWq6X4R5KtMWXm9Uhq8Mvc5cPkmchWmJtQIEvheaPzg0pqfBBPl/3gwUZSHpARu71qBaBvQ4sjAsUqNpLxa+uTPicf2LrbmyOZLaNkjYI9C7RmTxJhhLjLR13MOr8Sql5/rojJiriHVELSpCxzp2Yn/06reAqk95ILVZwj6GQstIDrPz5+SXq2rntpe7c7AJxurVjFIroMEe8J9eRqNr73XjugXUoD59S92/bihFY6RsrR32PlMaWGDgys9f3u4/puJ8V8S6sjl7INV6Wuyt6Biklf9G8V3C5MYFV4L3IZrFw/ai+2q1EnrcfnK59r2e4ylkdL/zZMk8IR+yZx0aK/Euu20CqNME/ziKKLA989IQBoKu0c7DOuquPe9B7MRCwKvP65DZ14jhs3vpUlzEmreP2KF1jmzvYHnNdVLb2NRRKCRj/szoKtYSwx1DjtWCoiEmoqQdrni5iabAKB3xhFuUF7pEF3jowb6ibc8vv4sqM2cTg8dXZikByupULpKwyVFDK8V91Qr0IHe9dwE=

after_success:
  - Rscript -e 'covr::codecov()'
